from .login_view import LoginView
from .main_window_view import MainView
from .home_view import HomeView
from .user_registration_view import UserRegistrationView
from .cadastro_manual_view import CadastroManualView
from .edicao_lote_view import EdicaoEmLoteView
from .gerenciar_colaboradores_view import GerenciarColaboradoresView
from .gerador_escala_view import GeradorEscalaView
from .gerenciar_sistema_view import GerenciarSistemaView